# Generated by Django 6.0.2 on 2026-02-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sport_name',
        ),
        migrations.CreateModel(
            name='SportsOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.TextField(choices=[('BAD', 'BADMINTON')])),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.product')),
            ],
        ),
    ]
