# Generated by Django 6.0.2 on 2026-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsports',
            name='sport',
            field=models.CharField(choices=[('BAD', 'Badminton'), ('BASKET', 'Basketball')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sportsPratique',
            field=models.CharField(blank=True, choices=[('BAD', 'Badminton'), ('BASKET', 'Basketball')], max_length=50, null=True),
        ),
    ]
