# Generated by Django 6.0.2 on 2026-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_remove_product_sport_name_sportsofproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportsofproduct',
            old_name='product_name',
            new_name='product',
        ),
    ]
