# Generated by Django 6.0.2 on 2026-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_product_image_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportproductrelation',
            name='sport',
            field=models.TextField(choices=[('BAD', 'Badminton'), ('BASKET', 'Basketball')]),
        ),
    ]
