# Generated by Django 6.0.2 on 2026-02-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatures',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productlevels',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productsports',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productstorestock',
            name='id',
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'position', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productimages',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'position', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productlevels',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'level', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productsports',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'sport', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productstorestock',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'store_name', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productsports',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.product'),
        ),
    ]
