# Generated by Django 6.0.2 on 2026-02-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_rename_product_name_sportsofproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
