# Generated by Django 6.0.2 on 2026-02-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_rename_product_name_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportLevelProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(choices=[('BEGINNER', 'Débutant'), ('AVERAGE', 'Intermediaire'), ('EXPERT', 'Expert')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.product')),
            ],
        ),
        migrations.CreateModel(
            name='SportProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.TextField(choices=[('BAD', 'Badminton')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.product')),
            ],
        ),
        migrations.DeleteModel(
            name='SportsOfProduct',
        ),
    ]
